### PR TITLE
Updated VARCHAR limit

### PR DESCRIPTION
**Pull request by Zohaib-Anwar**
Changed character limit for product name from 45 characters to 100.
pls approve.
i worked suuuper hard(not really but yes).

### CODE REVIEW

**Comment by Zohaib-Anwar** [comment]
i may be a bit dumb, please dont hate.
i think this is right but once again, the previous commits are still there

**Comment by mariuszskon** [comment]
Yeah look you are sorta dumb because you must have branched off something other than master again.
Simply run `git rebase master` while on the `new/varchar` branch to fix that, and force push.

**Comment by mariuszskon** [comment]
> Yeah look you are sorta dumb because you must have branched off something other than master again.
> Simply run `git rebase master` while on the `new/varchar` branch to fix that, and force push.

Make sure to checkout master, pull, and checkout `new/varchar` again first.

**Review by mariuszskon — APPROVED** [review]
LGTM

**Pull request merged**
